# アヤメの分類

## デフォルトインポート

In [1]:
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

warnings.filterwarnings('ignore')

%matplotlib inline

## データの準備

In [9]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

In [14]:
df = pd.DataFrame(X, columns=iris.feature_names)
df['y'] = y
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  y
0                5.1               3.5                1.4               0.2  0
1                4.9               3.0                1.4               0.2  0
2                4.7               3.2                1.3               0.2  0
3                4.6               3.1                1.5               0.2  0
4                5.0               3.6                1.4               0.2  0

## 数値モデルの構築

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['y']), df['y'], train_size=0.7, random_state=0)
print(X_train.shape, X_test.shape)

(105, 4) (45, 4)


In [17]:
# 分割後のバランス確認
np.bincount(y_train), np.bincount(y_test)

(array([34, 32, 39], dtype=int64), array([16, 18, 11], dtype=int64))

## 予測モデルの構築(ロジスティック回帰)

In [49]:
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## 予測してみる

In [50]:
X_new = np.array([
    [5.0, 3.5, 7.3, 10.8]
])
logistic_regression.predict(X_new)

array([2])

In [51]:
proba = logistic_regression.predict_proba(X_new)
print(f'{proba}')

[[6.79684403e-09 1.57024593e-05 9.99984291e-01]]


## 評価

In [56]:
acc_train = logistic_regression.score(X_train, y_train)
acc_test = logistic_regression.score(X_test, y_test)

print(f'Train Acc: {acc_train:.3f}')
print(f' Test Acc: {acc_test:.3f}')

Train Acc: 0.943
 Test Acc: 0.889


In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true=y_train, y_pred=logistic_regression.predict(X_train))

0.9428571428571428